# Product Colors
# Hightlights Group

- name: Hover Highlight
  hex: "FAFAFA"
  rgb: "250, 250, 250"
  sass: "$hover-highlight"

- name: Select Highlight
  hex: "FAFAFA"
  rgb: "250, 250, 250"
  sass: "$select-highlight"

- name: Inline Highlight
  hex: "E2E5E9"
  rgb: "226, 229, 233"
  sass: "$inline-highlight"
