# Product Colors
# Text Group

- name: Link
  hex: "0A83F6"
  rgb: "10, 131, 246"
  sass: "$link"

- name: Link Hover
  hex: "0769C6"
  rgb: "7, 105, 198"
  sass: "$link-hover"

- name: Text
  hex: "76899A"
  rgb: "118, 137, 154"
  sass: "$text"

- name: Heading
  hex: "57626C"
  rgb: "87, 98, 108"
  sass: "$heading"
